create database Akademik;
use Akademik;

create table FAKULTAS(
	ID_FAKULTAS smallint primary key,
	FAKULTAS VARCHAR(45) not NULL
);

create table JURUSAN(
	ID_JURUSAN smallint primary key,
	ID_FAKULTAS smallint references FAKULTAS(ID_FAKULTAS),
	JURUSAN VARCHAR(45) not NULL
);

create table STRATA(
	ID_STRATA smallint primary key,
	SINGKAT VARCHAR(10) not null,
	STRATA VARCHAR(45) not NULL
);

create table PROGRAM_STUDI(
	ID_PROGRAM_STUDI smallint primary key,
	ID_STRATA smallint references STRATA(ID_STRATA),
	ID_JURUSAN smallint references JURUSAN(ID_JURUSAN),
	PROGRAM_STUDI VARCHAR(60) not NULL
);

create table SELEKSI_MASUK(
	ID_SELEKSI_MASUK smallint primary key,
	SINGKAT VARCHAR(12) not null,
	SELEKSI_MASUK VARCHAR(60) not NULL
);

create table MAHASISWA(
	NIM VARCHAR(15) primary key,
	ID_SELEKSI_MASUK smallint references SELEKSI_MASUK(ID_SELEKSI_MASUK),
	ID_PROGRAM_STUDI smallint references PROGRAM_STUDI(ID_PROGRAM_STUDI),
	NAMA VARCHAR(45) not null,
	ANGKATAN smallint not null,
	TGL_LAHIR DATE not null,
	KOTA_LAHIR VARCHAR(60) not null,
	JENIS_KELAMIN CHAR(1) not null
);

use akademik;
INSERT INTO AKADEMIK.MAHASISWA
VALUES('155150404', 1,212,'JESSY',2016,'1999-2-10','BANDUNG','F'),
('155150405', 2 ,219,'BAMBANG',2014,'1996-9-27','MAKASSAR','M');

CREATE TABLE AKADEMIK.MAHASISWA_PINDAHAN(
NIM VARCHAR(15) NOT NULL PRIMARY KEY,
ID_SELEKSI_MASUK SMALLINT,
FOREIGN KEY (ID_SELEKSI_MASUK) REFERENCES AKADEMIK.SELEKSI_MASUK(ID_SELEKSI_MASUK),
ID_PROGRAM_STUDI SMALLINT,
FOREIGN KEY (ID_PROGRAM_STUDI) REFERENCES AKADEMIK.PROGRAM_STUDI(ID_PROGRAM_STUDI),
NAMA VARCHAR(45),
ANGKATAN SMALLINT,
TGL_LAHIR DATE,
KOTA_LAHIR VARCHAR(60),
JENIS_KELAMIN CHAR(1) CHECK (JENIS_KELAMIN IN ('M','F'))
);

INSERT INTO AKADEMIK.MAHASISWA_PINDAHAN
VALUES ('155150500', 1 ,211,'BUDI', 2015,'1997-3-3','BANYUWANGI','M'),
('155150501', 2,212,'ANDI',2015,'1997-2-21','JAKARTA','M'),
('155150502', 2 ,211,'DIMAS', 2015,'1998-4-11','SURABAYA','M'),
('155150503', 2 ,211,'DIDIN',2015,'1997-2-26','BANDUNG','M');

SELECT NIM, NAMA, JENIS_KELAMIN, KOTA_LAHIR, ANGKATAN
FROM Mahasiswa
WHERE KOTA_LAHIR LIKE 'B%'
UNION
SELECT NIM, NAMA, JENIS_KELAMIN, KOTA_LAHIR, ANGKATAN
FROM Mahasiswa_Pindahan
WHERE NAMA LIKE 'D%'
ORDER BY NIM;

SELECT NIM, NAMA, JENIS_KELAMIN, KOTA_LAHIR, ANGKATAN
FROM Mahasiswa
WHERE ANGKATAN = 2015
UNION
SELECT NIM, NAMA, JENIS_KELAMIN, KOTA_LAHIR, ANGKATAN
FROM Mahasiswa_Pindahan
WHERE ANGKATAN = 2015 AND KOTA_LAHIR NOT LIKE 'M%'
ORDER BY NIM;

SELECT M.NIM, M.NAMA, M.ANGKATAN
FROM Mahasiswa M
JOIN Mahasiswa_Pindahan MP ON M.KOTA_LAHIR = MP.KOTA_LAHIR
WHERE MP.NAMA = 'BUDI';

SELECT M.NIM, M.NAMA, M.ANGKATAN
FROM Mahasiswa M
WHERE M.KOTA_LAHIR IN (SELECT DISTINCT KOTA_LAHIR FROM Mahasiswa_Pindahan);




